# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
  - feature/*
  - bugfix/*

pool:
  vmImage: "ubuntu-latest"

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: build
    jobs:
      - job: "build"
        steps:
          - script: |
              curl https://get.volta.sh | bash
              export VOLTA_HOME=$HOME/.volta
              export PATH=$VOLTA_HOME/bin:$PATH
              volta list
          - script: npm install
            displayName: "npm install"
          - script: npm run build
            displayName: "npm run build"
  - stage: deploy
    condition: and(succeeded(), eq(variables.isMain, 'true'))
    variables:
      environment: "prod"
    jobs:
      - job: "publish"
        steps:
          - task: AzureCLI@1
            displayName: Create Environment
            inputs:
              azureSubscription: sc-honestybar-prod
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create --location "West Europe" --template-file ./azure/main.bicep --parameters environment='$(environment)'
          - task: AzureCLI@1
            displayName: Get deployment token
            inputs:
              azureSubscription: sc-honestybar-prod
              scriptLocation: inlineScript
              inlineScript: |
                apiKey=$(az staticwebapp secrets list --name app-kiosk-prod -g rg-frontend-kiosk-app-prod --query properties.apiKey -o tsv)
                echo "##vso[task.setvariable variable=AZURE_STATIC_WEB_APPS_API_TOKEN;issecret=true]$apiKey"
          - task: AzureStaticWebApp@0
            displayName: Deploy to static web app
            inputs:    
              # The App source code path
              app_location: "/"
              # Directory containing the built app content
              output_location: "dist"
              # The command used to build the app
              app_build_command: "npm run build"
              api_location: ""
              azure_static_web_apps_api_token: "$(AZURE_STATIC_WEB_APPS_API_TOKEN)"
